-- FOOD_TYPE과 FAVORITES만 있으면 상관없지만
-- 다른 값들도 조회해야 하기때문에 WHERE에서 MAX를 고르고 그것을 다시 선택해서 나열
SELECT
    FOOD_TYPE,
    REST_ID,
    REST_NAME,
    FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;